export const categoryMapping = {
    HeadwearCollection: "Headwear Collection",
    multifunctionalHeadwear: "Multifunctional Headwear",
    bucketHats: "Bucket Hats",
    beanies: "Beanies",
    FlatPeaks: "Flat Peaks",
    preCurvedPeaks: "Pre-Curved Peaks",
    hats: "Hats",
    newInHeadwear: "New In Headwear",
    truckerCaps: "Trucker Caps",
  };
  
  export const apparelCategoryMapping = {
    ApparelCollection: "Apparel Collection",
    newInApparel: "New in Apparel",
    men: "Men",
    women: "Women",
    kids: "Kids",
    tShirts: "T-Shirts",
    golfers: "Golfers",
    hoodies: "Hoodies",
    jackets: "Jackets",
    bottoms: "Bottoms",
  };
  
  export const allCollectionCategoryMapping = {
    signatureCollection: "Signature Collection",
    baseballCollection: "Baseball Collection",
    fashionCollection: "Fashion Collection",
    leisureCollection: "Leisure Collection",
    sportCollection: "Sport Collection",
    industrialCollection: "Industrial Collection",
    camoCollection: "Camo Collection",
    winterCollection: "Winter Collection",
    kidsCollection: "Kids Collection",
    africanCollection: "African Collection",
  };
  
  export const mockProducts = {
    HeadwearCollection: {
      headerImage: "/Headwear-collection-Header.jpg",
      products: [
        {
          id: "1",
          materials: "100% Acrylic Yarn",
          stock: "584",
          code: "1",
          name: "Ice Beanie",
          description:
            "Elevate your style while promoting sustainability and uplifting the planet...",
  
          fit: "One Size Fits Most",
          variants: [
            {
              type: "color",
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/ice-beanie-black-.jpg",
              code: "IB-BLK-001",
              size: "OSFM",
            },
            {
              type: "color",
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/ice-beanie-navy-.jpg",
              code: "IB-NVY-001",
              size: "OSFM",
            },
            {
              type: "color",
              name: "Charcoal",
              hex: "#433b42",
              stock: 580,
              price: "R29.99",
              image: "/ice-beanie-charcoal-.jpg",
              code: "IB-CHL-001",
              size: "OSFM",
            },
            {
              type: "color",
              name: "Dusty Pink",
              hex: "#da8170",
              stock: 628,
              price: "R29.99",
              image: "/ice-beanie-dusty-pink-.jpg",
              code: "IB-DP-001",
              size: "OSFM",
            },
            {
              type: "color",
              name: "Burgundy",
              hex: "#400c19",
              stock: 800,
              price: "R29.99",
              image: "/ice-beanie-burgundy-.jpg",
              code: "IB-BRG-001",
              size: "OSFM",
            },
            {
              type: "color",
              name: "Bottle",
              hex: "#1d402f",
              stock: 368,
              price: "R29.99",
              image: "/ice-beanie-bottle-.jpg",
              code: "IB-BTT-001",
              size: "OSFM",
            },
            {
              type: "color",
              name: "Olive",
              hex: "#343219",
              stock: 658,
              price: "R29.99",
              image: "/ice-beanie-olive-.jpg",
              code: "IB-OLI-001",
              size: "OSFM",
            },
            {
              type: "color",
              name: "Tan",
              hex: "#d1a26a",
              stock: 458,
              price: "R29.99",
              image: "/ice-beanie-tan-.jpg",
              code: "IB-TAN-001",
              size: "OSFM",
            },
            {
              type: "color",
              name: "Mustard",
              hex: "#ef7d1d",
              stock: 758,
              price: "R29.99",
              image: "/ice-beanie-mustard-.jpg",
              code: "IB-MTD-001",
              size: "OSFM",
            },
            {
              type: "color",
              name: "Burnt Orange",
              hex: "#ca1e0d",
              stock: 985,
              price: "R29.99",
              image: "/ice-beanie-burnt-orange-.jpg",
              code: "IB-BO-001",
              size: "OSFM",
            },
            {
              type: "color",
              name: "Grey",
              hex: "#c2b3b4",
              stock: 825,
              price: "R29.99",
              image: "/ice-beanie-grey-.jpg",
              code: "IB-GRY-001",
              size: "OSFM",
            },
          ],
          gender: "Female",
  
          title: "Ice Beanie",
          rating: 4.5,
          price: "R29.99",
          status: "new", // 'soldout' or 'new'
          image: "/ice-beanie-dusty-pink-.jpg",
          image2: "/ice-beanie-burnt-orange-.jpg",
          image3: "/ice-beanie-tan-.jpg",
          image4: "/ice-beanie-black-.jpg",
          image5: "/ice-beanie-burgundy-.jpg",
          image6: "/ice-beanie-charcoal-.jpg",
          image7: "/ice-beanie-grey-.jpg",
          image8: "/ice-beanie-mustard-.jpg",
          image9: "/ice-beanie-navy-.jpg",
          image10: "/ice-beanie-olive-.jpg",
          image11: "/ice-beanie-bottle-.jpg",
        },
        {
          id: "2",
          materials: "60% cotton, 40% polyester",
  
          stock: "",
          code: "",
          name: "Original Trucker Camo",
          variants: [
            {
              type: "image",
              name: "Original-Trucker-Camo-Green",
              hex: "#c2b3b4",
              stock: 825,
              price: "R29.99",
              image: "/Original-Trucker-Camo-Green-Soc1.jpg",
              code: "IB-GRY-001",
              size: "OSFM",
              stock: 758,
            },
            {
              type: "image",
              name: "Original-Trucker-Camo-Green",
              hex: "#c2b3b4",
              stock: 825,
              price: "R29.99",
              image: "/Original-Trucker-Camo-Woodland-Boc1.jpg",
              code: "IB-GRY-001",
              size: "OSFM",
              stock: 758,
            },
            {
              type: "image",
              name: "Original-Trucker-Camo-Green",
  
              hex: "#c2b3b4",
              stock: 825,
              price: "R29.99",
              image: "/Original-Trucker-Camo-Green-Foc1.jpg",
              code: "IB-GRY-001",
              size: "OSFM",
              stock: 758,
            },
          ],
          thumbnails: [
            {
              type: "image",
              name: "Original-Trucker-Camo-forrest",
              image: "/Original-Trucker-Camo-forrest-Foc1.jpg",
              stock: 500,
              price: "R29.99",
              stock: 200,
              code: "IB-GRY-001",
              size: "OSFM",
            },
            {
              type: "image",
              name: "Original-Trucker-Camo-Woodland",
              image: "/Original-Trucker-Camo-Woodland-Foc1.jpg",
              stock: 825,
              price: "R29.99",
              stock: 758,
              code: "IB-GRY-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Original Trucker Camo",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Original-Trucker-Camo-model-1.jpeg",
          image2: "/Original-Trucker-Camo-Green-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "3",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "American Two Tone Cap",
          rating: 4.0,
          price: "R25.99",
          status: "soldout",
          image: "/American-Two-Tone-Grey-Melange-Navy-Foc1.jpg",
          image2: "/American-Two-Tone-Grey-Melange-Black-Soc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "4",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Venture Hat Royal Boc",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Venture-Hat-model-scaled.webp",
          image2: "/Venture-Hat-Royal-Boc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "5",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Savannah Hat Dark Khaki",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Savannah-Hat-model.jpg",
          image2: "/Savannah-Hat-Dark-Khaki-foc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "6",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Supafit Red",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image2: "/Supafit-Red-Foc.jpg",
          image: "/Supafit-new-model.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "7",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Harlem Bucket",
          rating: 4.0,
          price: "R25.99",
          status: "soldout",
          image: "/Harlem-Bucket-model(1).jpg",
          image2: "/Harlem-Bucket-Hat-Charcoal-1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "8",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Linen lilac",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Linen-model.jpg",
          image2: "/Linen-lilac-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "9",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Camper Trucker",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Camper-Trucker-model.jpg",
          image2: "/Camper-Trucker-Raspberry-Khaki-Foc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "10",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Barista Apron",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Barista-Apron-model.jpg",
          image2: "/Barista-Apron-Black1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  
    FlatPeaks: {
      headerImage: "/take-away-background-and-clean-up-small.jpg",
      products: [
        {
          id: "11",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "A-Frame Trucker Cap",
          rating: 4.5,
          price: 29.99,
          status: "new", // 'soldout' or 'new'
          image: "/A-Frame-White-Foc.jpg",
          image2: "/A-Frame-White-Soc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "12",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "13",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
    beanies: {
      headerImage: "/139A1795-Web.jpg",
      products: [
        {
          id: "14",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "A-Frame Trucker Cap",
          rating: 4.5,
          price: 29.99,
          status: "new", // 'soldout' or 'new'
          image: "/A-Frame-White-Foc.jpg",
          image2: "/A-Frame-White-Soc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "15",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "16",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
    bucketHats: {
      headerImage: "/Venture-Hat.jpg",
      products: [
        {
          id: "17",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "A-Frame Trucker Cap",
          rating: 4.5,
          price: 29.99,
          status: "new", // 'soldout' or 'new'
          image: "/A-Frame-White-Foc.jpg",
          image2: "/A-Frame-White-Soc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "18",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "19",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
    hats: {
      headerImage: "/Camo-Collection-2022-2.jpg",
      products: [
        {
          id: "20",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "A-Frame Trucker Cap",
          rating: 4.5,
          price: 29.99,
          status: "new", // 'soldout' or 'new'
          image: "/A-Frame-White-Foc.jpg",
          image2: "/A-Frame-White-Soc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "21",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "22",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
    multifunctionalHeadwear: {
      headerImage: "/Multifuctional-Headwear-Camo-model.jpg",
      products: [
        {
          id: "23",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "A-Frame Trucker Cap",
          rating: 4.5,
          price: 29.99,
          status: "new", // 'soldout' or 'new'
          image: "/A-Frame-White-Foc.jpg",
          image2: "/A-Frame-White-Soc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "24",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "25",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
    newInHeadwear: {
      headerImage: "/new-in-headwear.jpg",
      products: [
        {
          id: "26",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "A-Frame Trucker Cap",
          rating: 4.5,
          price: 29.99,
          status: "new", // 'soldout' or 'new'
          image: "/A-Frame-White-Foc.jpg",
          image2: "/A-Frame-White-Soc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "27",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "28",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
    preCurvedPeaks: {
      headerImage: "/new-in-headwear.jpg",
      products: [
        {
          id: "29",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "A-Frame Trucker Cap",
          rating: 4.5,
          price: 29.99,
          status: "new", // 'soldout' or 'new'
          image: "/A-Frame-White-Foc.jpg",
          image2: "/A-Frame-White-Soc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "30",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "31",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
    truckerCaps: {
      headerImage: "/139A8512-b-smal.jpg",
      products: [
        {
          id: "32",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "A-Frame Trucker Cap",
          rating: 4.5,
          price: 29.99,
          status: "new", // 'soldout' or 'new'
          image: "/A-Frame-White-Foc.jpg",
          image2: "/A-Frame-White-Soc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "33",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "34",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "35",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Supafit Red",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image2: "/Supafit-Red-Foc.jpg",
          image: "/Supafit-new-model.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "36",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Harlem Bucket",
          rating: 4.0,
          price: "R25.99",
          status: "soldout",
          image: "/Harlem-Bucket-model(1).jpg",
          image2: "/Harlem-Bucket-Hat-Charcoal-1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "37",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Linen lilac",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Linen-model.jpg",
          image2: "/Linen-lilac-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "38",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Camper Trucker",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Camper-Trucker-model.jpg",
          image2: "/Camper-Trucker-Raspberry-Khaki-Foc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "39",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Barista Apron",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Barista-Apron-model.jpg",
          image2: "/Barista-Apron-Black1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  };
  
  export const apparelMockProducts = {
    ApparelCollection: {
      headerImage: "/Apparel-Collection-2022-1.jpg",
      products: [
        {
          id: "40",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "41",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "42",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "43",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Supafit Red",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image2: "/Supafit-Red-Foc.jpg",
          image: "/Supafit-new-model.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "44",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Harlem Bucket",
          rating: 4.0,
          price: "R25.99",
          status: "soldout",
          image: "/Harlem-Bucket-model(1).jpg",
          image2: "/Harlem-Bucket-Hat-Charcoal-1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "45",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Linen lilac",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Linen-model.jpg",
          image2: "/Linen-lilac-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "46",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Camper Trucker",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Camper-Trucker-model.jpg",
          image2: "/Camper-Trucker-Raspberry-Khaki-Foc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "47",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Barista Apron",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Barista-Apron-model.jpg",
          image2: "/Barista-Apron-Black1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  
    newInApparel: {
      headerImage: "/new-in-apparel-bg.jpg",
      products: [
        {
          id: "48",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "49",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
    men: {
      headerImage: "/Americano-model-scaled.jpg",
      products: [
        {
          id: "50",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "51",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "52",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "53",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Supafit Red",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image2: "/Supafit-Red-Foc.jpg",
          image: "/Supafit-new-model.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  
    women: {
      headerImage: "/Ladies_Golfer-model.jpg",
      products: [
        {
          id: "54",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
      ],
    },
  
    kids: {
      headerImage: "/kids-collection-bg1.jpg",
      products: [
        {
          id: "55",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "56",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  
    //T-Shirts
    tShirts: {
      headerImage: "/Kids-Promo-T-Shirt-Lime2.jpg",
      products: [
        {
          id: "57",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
      ],
    },
  
    //Golfers
    golfers: {
      headerImage: "/Mens-Golfer-model.jpg",
      products: [
        {
          id: "58",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
      ],
    },
  
    //Hoodies
    hoodies: {
      headerImage: "/Base-Hoodie-model.jpg",
      products: [
        {
          id: "59",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
      ],
    },
  
    //Jackets
    jackets: {
      headerImage: "/Alaska-Puffer-Jacket-Black.jpg",
      products: [
        {
          id: "60",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "61",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  
    //Bottoms
    bottoms: {
      headerImage: "/Jogger-sml.jpg",
      products: [
        {
          id: "62",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "63",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "64",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "65",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Supafit Red",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image2: "/Supafit-Red-Foc.jpg",
          image: "/Supafit-new-model.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "66",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Harlem Bucket",
          rating: 4.0,
          price: "R25.99",
          status: "soldout",
          image: "/Harlem-Bucket-model(1).jpg",
          image2: "/Harlem-Bucket-Hat-Charcoal-1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "67",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Linen lilac",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Linen-model.jpg",
          image2: "/Linen-lilac-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  };
  
  //All Collections Mock Productions
  export const allCollectionMockProducts = {
    //signature collection
    signatureCollection: {
      headerImage: "/Signature-Collection-Header.jpg",
      products: [
        {
          id: "40",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "41",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "42",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "43",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Supafit Red",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image2: "/Supafit-Red-Foc.jpg",
          image: "/Supafit-new-model.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "44",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Harlem Bucket",
          rating: 4.0,
          price: "R25.99",
          status: "soldout",
          image: "/Harlem-Bucket-model(1).jpg",
          image2: "/Harlem-Bucket-Hat-Charcoal-1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "45",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Linen lilac",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Linen-model.jpg",
          image2: "/Linen-lilac-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "46",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Camper Trucker",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Camper-Trucker-model.jpg",
          image2: "/Camper-Trucker-Raspberry-Khaki-Foc.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "47",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Barista Apron",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image: "/Barista-Apron-model.jpg",
          image2: "/Barista-Apron-Black1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  
    baseballCollection: {
      headerImage: "/Baseball-Collection-Header.jpg",
      products: [
        {
          id: "48",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "49",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  
    //fashion collection
    fashionCollection: {
      headerImage: "/Fashion-collection-Header-01.jpg",
      products: [
        {
          id: "54",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
      ],
    },
  
    //leisure collection
    leisureCollection: {
      headerImage: "/Leisure-collection-Header.jpg",
      products: [
        {
          id: "55",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "56",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  
    //sport collection
    sportCollection: {
      headerImage: "/Sport-collection-Header-1.jpg",
      products: [
        {
          id: "57",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
      ],
    },
  
    //industrial collection
    industrialCollection: {
      headerImage: "/Industrial-collection-Btn.jpg",
      products: [
        {
          id: "50",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "51",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "52",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "53",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Supafit Red",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image2: "/Supafit-Red-Foc.jpg",
          image: "/Supafit-new-model.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  
    //camo collection
    camoCollection: {
      headerImage: "/camo-collection-Header-scaled.webp",
      products: [
        {
          id: "50",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "51",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "52",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Signature Snapback Cap",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Signature-Snapback-Denim-model.jpg",
          image2: "/Signature-Snapback-Grey-Melange-Black-Foc-01.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
        {
          id: "53",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Supafit Red",
          rating: 4.0,
          price: "R25.99",
          status: " ",
          image2: "/Supafit-Red-Foc.jpg",
          image: "/Supafit-new-model.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  
    //winter collection
    winterCollection: {
      headerImage: "/winter-collection-Header.jpg",
      products: [
        {
          id: "58",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
      ],
    },
  
    //kids collection
    kidsCollection: {
      headerImage: "/kids-collection-bg1.jpg",
      products: [
        {
          id: "59",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
      ],
    },
  
    //african collection
    africanCollection: {
      headerImage: "/African-Collection-header2.jpg",
      products: [
        {
          id: "60",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [
            {
              name: "Black",
              hex: "#000000",
              stock: 100,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Black.jpg",
              code: "ATLS-BLK-001",
              size: "OSFM",
            },
            {
              name: "Navy",
              hex: "#37364c",
              stock: 235,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Navy.jpg",
              code: "ATLS-NVY-001",
              size: "OSFM",
            },
            {
              name: "Red",
              hex: "#FF0000",
              stock: 580,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Red.jpg",
              code: "ATLS-RED-001",
              size: "OSFM",
            },
            {
              name: "Grey",
              hex: "#708090",
              stock: 628,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
              code: "ATLS-GRY-001",
              size: "OSFM",
            },
            {
              name: "White",
              hex: "#FFFFFF",
              stock: 800,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-White.jpg",
              code: "ATLS-WHT-001",
              size: "OSFM",
            },
            {
              name: "Royal",
              hex: "#4169e1",
              stock: 368,
              price: "R29.99",
              image: "/Activ-T-Long-Sleeve-Royal.jpg",
              code: "ATLS-RYL-001",
              size: "OSFM",
            },
          ],
          fit: "",
          gender: "",
          title: "Activ-T Long Sleeve",
          rating: 4.5,
          price: 29.99,
          status: "", // 'soldout' or 'new'
          image: "/Activ-T-Long-Sleeve-Royal.jpg",
          image2: "/Premium-Long-Sleeve-T-Shirt-Stone-scaled.jpg",
          image3: "/Activ-T-Long-Sleeve-Black.jpg",
          image4: "/Activ-T-Long-Sleeve-Navy.jpg",
          image5: "/Activ-T-Long-Sleeve-Red.jpg",
          image6: "/Activ-T-Long-Sleeve-Slate-Grey.jpg",
          image7: "/Activ-T-Long-Sleeve-White.jpg",
        },
        {
          id: "61",
          materials: "60% cotton, 40% polyester",
          stock: "",
          code: "",
          name: "",
          colors: [""],
          fit: "",
          gender: "",
          title: "Snapback",
          rating: 4.0,
          price: "R25.99",
          status: "",
          image: "/Snapback-Red-Foc-1.jpg",
          image2: "/Snapback-Charcoal-Foc1.jpg",
          image3: "",
          image4: "",
          image5: "",
        },
      ],
    },
  };
  